version: '3'

services:
  node1:
    container_name: node1-management
    build:
      context: ./node1
      dockerfile: Dockerfile
    ports:
      - "4001:3001"
    environment:
      - PORT=3001
  
  node2:
    container_name: node2-management
    build:
      context: ./node2
      dockerfile: Dockerfile
    ports:
      - "4002:3002"
    environment:
      - PORT=3002
      # - MESSAGE_BUS=amqp://rabbitmq
    
  
  node3:
    container_name: node3-management
    build:
      context: ./node3
      dockerfile: Dockerfile
    ports:
      - "4003:3003"
    environment:
      - PORT=3003
    #   - MESSAGE_BUS=amqp://rabbitmq
    # links:
    #   - rabbitmq
  
  # authentication:
  #   container_name: authentication
  #   build:
  #     context: ./services/authentication
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3003:3000"
  #   environment:
  #     - PORT=3000
  #     - MESSAGE_BUS=amqp://rabbitmq
  #   links:
  #     - rabbitmq
  
  # notification:
  #   container_name: notification
  #   build:
  #     context: ./services/notification
  #     dockerfile: Dockerfile
  #   environment:
  #     - MESSAGE_BUS=amqp://rabbitmq
  #     - EMAIL_SERVICE=gmail
  #     - EMAIL_ID=noreply.localnewsapplication@gmail.com
  #     - EMAIL_PASSWORD=Testing0*
  #     - ADMIN_EMAIL=localnewsapp340ct@gmail.com
  #   links:
  #     - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.4